import { WatchCardProps } from '@/components/shared/watch-card';

export const mockWatches: WatchCardProps[] = [
    {
        id: '1',
        name: 'Rado Manhattan - No reserve price - "Graphite Noir" Automatic',
        brand: 'Rado',
        price: 9500000,
        originalPrice: 12000000,
        condition: 'excellent',
        year: '1978',
        image: '/images/watches/watch-1.png',
        isNew: false,
        isFeatured: false,
    },
    {
        id: '2',
        name: 'Rado Masterborn - No reserve price - JD003333 - Men - 1970',
        brand: 'Rado',
        price: 5500000,
        condition: 'good',
        year: '1970',
        image: '/images/watches/watch-2.png',
        isNew: false,
        isFeatured: true,
    },
    {
        id: '3',
        name: 'Rado Stag - No reserve price - 610MG1474 - Men - 1978',
        brand: 'Rado',
        price: 10500000,
        condition: 'like-new',
        year: '1978',
        image: '/images/watches/watch-3.png',
        isNew: true,
        isFeatured: false,
    },
    {
        id: '4',
        name: 'Rado Conway II - No reserve price - 11914/1 - Men - 1970-1979',
        brand: 'Rado',
        price: 4300000,
        condition: 'good',
        year: '1975',
        image: '/images/watches/watch-4.png',
        isNew: false,
        isFeatured: false,
    },
    {
        id: '5',
        name: 'Rado Gazelle - No reserve price caliber AS 1536 - Men - 1960-1969',
        brand: 'Rado',
        price: 3800000,
        condition: 'fair',
        year: '1965',
        image: '/images/watches/watch-5.png',
        isNew: false,
        isFeatured: false,
    },
    {
        id: '6',
        name: 'Rado Manhattan III - No reserve price - 633.3042.4 - Men - 1970',
        brand: 'Rado',
        price: 8000000,
        condition: 'excellent',
        year: '1970',
        image: '/images/watches/watch-6.png',
        isNew: false,
        isFeatured: true,
    },
    {
        id: '7',
        name: 'Rado Serbia - No reserve price - BRC702 - Men - 1975-1979',
        brand: 'Rado',
        price: 7000000,
        condition: 'excellent',
        year: '1977',
        image: '/images/watches/watch-7.png',
        isNew: false,
        isFeatured: false,
    },
    {
        id: '8',
        name: 'Rado Schillman - No reserve price - 72364648 - Men - 1979',
        brand: 'Rado',
        price: 8800000,
        condition: 'like-new',
        year: '1979',
        image: '/images/watches/watch-8.png',
        isNew: false,
        isFeatured: false,
    },
    {
        id: '9',
        name: 'Omega Geneve - No reserve price - 515 003 - Women - 1963',
        brand: 'Omega',
        price: 10200000,
        originalPrice: 12500000,
        condition: 'excellent',
        year: '1963',
        image: '/images/watches/watch-9.png',
        isNew: true,
        isFeatured: false,
    },
    {
        id: '10',
        name: 'Omega Geneve "Hair Elegant" - No reserve price - 966 021',
        brand: 'Omega',
        price: 8700000,
        condition: 'good',
        year: '1969',
        image: '/images/watches/watch-10.png',
        isNew: false,
        isFeatured: false,
    },
    {
        id: '11',
        name: 'Omega De Ville "Petite Espace" - No reserve price - 511 166',
        brand: 'Omega',
        price: 3500000,
        condition: 'fair',
        year: '1972',
        image: '/images/watches/watch-11.png',
        isNew: false,
        isFeatured: true,
    },
    {
        id: '12',
        name: 'Seiko Lord Matic 輝 (Girly) - Silver Subnorce - No reserve',
        brand: 'Seiko',
        price: 4100000,
        condition: 'excellent',
        year: '1975',
        image: '/images/watches/watch-12.png',
        isNew: false,
        isFeatured: false,
    },
];
